---
output: 
  html_document:
    css: docs.css
---

#### Currently, how many infections can be generated by an infectious person. The expected number is $R(t)$.  

### Why is this important?

- Apart from the basic transmission properties, $R(t)$ considers the herd immunity. 
- $R(t)$ shows if an epidemic is still in an outbreak status or dying out. 


 
### What we need to estimate

- Estimators of incidence give a time point. 
- Rates of immune response or isolation.
- (*) There are many methods for $R(t)$ estimation. Different methods have different requirements


### However, $R(t)$ might be underestimated because

- The risk of re-infection and relapse
- Once the antibody does not provide full immunity


### FAQ
**When $R(t) < 1$, we are safe**

- Not exactly. $R(t) < 1$ indicates the incidence is declining, but it doesn't mean the infection is eliminated. 


**Is $R(t)$ always declining?**

- The changes in human behaviour and temperature might cause different transmissibility. Also, the pathogen might mutate and adapt to the environment.  
